CREATE TABLE IF NOT EXISTS messages (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL DEFAULT '',
  photo TEXT NOT NULL DEFAULT '',
  text VARCHAR(280) DEFAULT '',
  sequence BIGSERIAL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS messages_created_at_idx ON messages (created_at DESC);
CREATE INDEX IF NOT EXISTS messages_sequence_idx ON messages (sequence DESC);

ALTER TABLE messages ADD COLUMN IF NOT EXISTS name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS photo TEXT NOT NULL DEFAULT '';
ALTER TABLE messages ALTER COLUMN text DROP NOT NULL;
